/* tslint:disable */
/* eslint-disable */
/**
 * Todo API
 * A simple todo list API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface GithubComDunstormMySvelteGoTemplateBackendInternalModelsTodo
 */
export interface GithubComDunstormMySvelteGoTemplateBackendInternalModelsTodo {
    /**
     * 
     * @type {boolean}
     * @memberof GithubComDunstormMySvelteGoTemplateBackendInternalModelsTodo
     */
    'completed'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof GithubComDunstormMySvelteGoTemplateBackendInternalModelsTodo
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof GithubComDunstormMySvelteGoTemplateBackendInternalModelsTodo
     */
    'title'?: string;
}

/**
 * TodosApi - axios parameter creator
 * @export
 */
export const TodosApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get a list of all todo items
         * @summary Get all todos
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiTodosGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/todos`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Update a todo\'s completion status
         * @summary Update a todo
         * @param {number} id Todo ID
         * @param {GithubComDunstormMySvelteGoTemplateBackendInternalModelsTodo} todo Todo object
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiTodosIdPut: async (id: number, todo: GithubComDunstormMySvelteGoTemplateBackendInternalModelsTodo, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiTodosIdPut', 'id', id)
            // verify required parameter 'todo' is not null or undefined
            assertParamExists('apiTodosIdPut', 'todo', todo)
            const localVarPath = `/api/todos/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(todo, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Create a new todo item with the provided title
         * @summary Create a new todo
         * @param {GithubComDunstormMySvelteGoTemplateBackendInternalModelsTodo} todo Todo object
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiTodosPost: async (todo: GithubComDunstormMySvelteGoTemplateBackendInternalModelsTodo, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'todo' is not null or undefined
            assertParamExists('apiTodosPost', 'todo', todo)
            const localVarPath = `/api/todos`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(todo, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TodosApi - functional programming interface
 * @export
 */
export const TodosApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TodosApiAxiosParamCreator(configuration)
    return {
        /**
         * Get a list of all todo items
         * @summary Get all todos
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiTodosGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<GithubComDunstormMySvelteGoTemplateBackendInternalModelsTodo>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiTodosGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TodosApi.apiTodosGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Update a todo\'s completion status
         * @summary Update a todo
         * @param {number} id Todo ID
         * @param {GithubComDunstormMySvelteGoTemplateBackendInternalModelsTodo} todo Todo object
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiTodosIdPut(id: number, todo: GithubComDunstormMySvelteGoTemplateBackendInternalModelsTodo, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GithubComDunstormMySvelteGoTemplateBackendInternalModelsTodo>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiTodosIdPut(id, todo, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TodosApi.apiTodosIdPut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Create a new todo item with the provided title
         * @summary Create a new todo
         * @param {GithubComDunstormMySvelteGoTemplateBackendInternalModelsTodo} todo Todo object
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiTodosPost(todo: GithubComDunstormMySvelteGoTemplateBackendInternalModelsTodo, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GithubComDunstormMySvelteGoTemplateBackendInternalModelsTodo>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiTodosPost(todo, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TodosApi.apiTodosPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * TodosApi - factory interface
 * @export
 */
export const TodosApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TodosApiFp(configuration)
    return {
        /**
         * Get a list of all todo items
         * @summary Get all todos
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiTodosGet(options?: RawAxiosRequestConfig): AxiosPromise<Array<GithubComDunstormMySvelteGoTemplateBackendInternalModelsTodo>> {
            return localVarFp.apiTodosGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Update a todo\'s completion status
         * @summary Update a todo
         * @param {number} id Todo ID
         * @param {GithubComDunstormMySvelteGoTemplateBackendInternalModelsTodo} todo Todo object
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiTodosIdPut(id: number, todo: GithubComDunstormMySvelteGoTemplateBackendInternalModelsTodo, options?: RawAxiosRequestConfig): AxiosPromise<GithubComDunstormMySvelteGoTemplateBackendInternalModelsTodo> {
            return localVarFp.apiTodosIdPut(id, todo, options).then((request) => request(axios, basePath));
        },
        /**
         * Create a new todo item with the provided title
         * @summary Create a new todo
         * @param {GithubComDunstormMySvelteGoTemplateBackendInternalModelsTodo} todo Todo object
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiTodosPost(todo: GithubComDunstormMySvelteGoTemplateBackendInternalModelsTodo, options?: RawAxiosRequestConfig): AxiosPromise<GithubComDunstormMySvelteGoTemplateBackendInternalModelsTodo> {
            return localVarFp.apiTodosPost(todo, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TodosApi - object-oriented interface
 * @export
 * @class TodosApi
 * @extends {BaseAPI}
 */
export class TodosApi extends BaseAPI {
    /**
     * Get a list of all todo items
     * @summary Get all todos
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TodosApi
     */
    public apiTodosGet(options?: RawAxiosRequestConfig) {
        return TodosApiFp(this.configuration).apiTodosGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Update a todo\'s completion status
     * @summary Update a todo
     * @param {number} id Todo ID
     * @param {GithubComDunstormMySvelteGoTemplateBackendInternalModelsTodo} todo Todo object
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TodosApi
     */
    public apiTodosIdPut(id: number, todo: GithubComDunstormMySvelteGoTemplateBackendInternalModelsTodo, options?: RawAxiosRequestConfig) {
        return TodosApiFp(this.configuration).apiTodosIdPut(id, todo, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Create a new todo item with the provided title
     * @summary Create a new todo
     * @param {GithubComDunstormMySvelteGoTemplateBackendInternalModelsTodo} todo Todo object
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TodosApi
     */
    public apiTodosPost(todo: GithubComDunstormMySvelteGoTemplateBackendInternalModelsTodo, options?: RawAxiosRequestConfig) {
        return TodosApiFp(this.configuration).apiTodosPost(todo, options).then((request) => request(this.axios, this.basePath));
    }
}



